//
// PersoncontrollerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class PersoncontrollerAPI: APIBase {
    /**
     findAll
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func findAllUsingGET(completion: @escaping ((_ data: [Person]?,_ error: Error?) -> Void)) {
        findAllUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     findAll
     - GET /person
     - examples: [{output=none}]

     - returns: RequestBuilder<[Person]> 
     */
    open class func findAllUsingGETWithRequestBuilder() -> RequestBuilder<[Person]> {
        let path = "/person"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Person]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     save
     
     - parameter id: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter lastname: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func saveUsingPOST(id: Int64? = nil, name: String? = nil, lastname: String? = nil, completion: @escaping ((_ data: Person?,_ error: Error?) -> Void)) {
        saveUsingPOSTWithRequestBuilder(id: id, name: name, lastname: lastname).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     save
     - POST /person
     - examples: [{output=none}]
     
     - parameter id: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter lastname: (query)  (optional)

     - returns: RequestBuilder<Person> 
     */
    open class func saveUsingPOSTWithRequestBuilder(id: Int64? = nil, name: String? = nil, lastname: String? = nil) -> RequestBuilder<Person> {
        let path = "/person"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "id": id?.encodeToJSON(), 
            "name": name, 
            "lastname": lastname
        ])
        

        let requestBuilder: RequestBuilder<Person>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
